# Generated by Django 4.0.4 on 2023-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_assistant',
            field=models.BooleanField(default=False),
        ),
    ]
