# Generated by Django 4.0.4 on 2023-11-13 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_myuser_is_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('familya', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=50)),
                ('vaqt', models.CharField(max_length=50)),
                ('kun', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('assis', 'ASSISTANT'), ('teacher', 'TEACHER'), ('user', 'USER')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='Gruhlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yunalishi', models.CharField(max_length=50)),
                ('vaqt', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
