# Generated by Django 4.0.4 on 2023-11-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_student_myuser_status_gruhlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_assistant',
        ),
    ]
