# Generated by Django 4.0.4 on 2023-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_myuser_is_assistant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='status',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'Yordamchi'), ('teacher', "O'qituvchi")], default='user', max_length=20),
        ),
    ]
