# Generated by Django 4.0.4 on 2023-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_myuser_status_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.AddField(
            model_name='myuser',
            name='fan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gruhi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='status',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('assis', 'ASSISTANT'), ('teacher', 'TEACHER'), ('user', 'USER')], default='user', max_length=50),
        ),
    ]
