# Generated by Django 4.0.4 on 2023-11-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_myuser_role_myuser_fan_myuser_gruhi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='fan',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gruhi',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='familya',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='student',
            name='kun',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vaqt',
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'Yordamchi'), ('teacher', "O'qituvchi")], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Gruhlar',
        ),
    ]
